### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CarlosAndre2111** [zhaochenqiu/UBgS_ADNNet#1]
Hello!

I have been reading your paper and due to the great performance that it shows I would like to implement it for my thesis, so I have a little question about the environment:

Is there any version of Python and Pytorch that you recommend in particular?

Thanks.

**Comment by zhaochenqiu** [comment]
Hello, pls check the environment details: conda 4.12.0, python 3.7.13, CUDA 10.1, torch 1.7.1. My GPU card is GTX 1080 with driver version 430.64
