### ISSUE TITLE
common_py files are missing

### ISSUE THREAD

**Issue by RMalikM** [zhaochenqiu/UBgS_ADNNet#2]
Hi @zhaochenqiu,
I was trying to run the demo after cloning the repo but I got the following error:
ModuleNotFoundError: No module named 'common_py.dataIO'

I found that there are no files in common_py folder. Could you please look into that?
Thanks

**Comment by zhaochenqiu** [comment]
Hi RmalikM, missing files have been uploaded. Thanks!

**Comment by RMalikM** [comment]
Thanks for the updates. I am closing it now.
